# fly.toml app configuration file generated for go-tools on 2026-08-08T11:47:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-tools'
primary_region = 'sin'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
